language: python # This lets us use newer python versions from virtualenv
python: "3.5"
compiler: clang
dist: trusty
sudo: false
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.ccache
  timeout: 1000

matrix:
  fast_finish: true
  include:
      ##########################################################
      # QGIS TESTS ON BIONIC
      ##########################################################
    - os: linux
      services: docker
      env:
        - TRAVIS_CONFIG=linux
        - DOCKER_COMPOSE=${TRAVIS_BUILD_DIR}/.docker/docker-compose.travis.yml
        # TRAVIS_BRANCH is either the git tag or the branch name when no tag
        - DOCKER_TAG=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && echo $TRAVIS_BRANCH | sed 's/master/latest/' || echo "latest" )
        - TRAVIS_TIMESTAMP=$(date +%s)
        - CCACHE_DIR=${HOME}/.ccache
      if: type!=cron

      ##########################################################
      # CODE LAYOUT
      ##########################################################
    
      env:
        - TRAVIS_CONFIG=code_layout
      addons:
        apt:
          sources:
            - sourceline: 'ppa:jonathonf/backports'  # silversearcher-ag backport
            - sourceline: 'ppa:sergey-dryabzhinsky/packages' # doxygen
          packages:
            - doxygen
            - graphviz
            - txt2tags
            - pkg-config
            - xvfb
            - flip
            # used for spell checks
            - perl  # sipify, lookahead regex in spell check script
            - silversearcher-ag
            - expect-dev  # unbuffer
            - coreutils
            # dependencies for licensecheck
            - cpanminus
            - libyaml-tiny-perl
            - libio-socket-ssl-perl
            - libhttp-date-perl
            - libgetopt-long-descriptive-perl
            - libmoo-perl
            - libnamespace-clean-perl
            - libpath-tiny-perl
            - libpod-constants-perl
            - libscalar-list-utils-perl
            - libsort-key-perl
            - libstrictures-perl
            - libstring-escape-perl
            - libtry-tiny-perl



      ##########################################################
      #
      #  DOCKER IMAGE BUILD JOBS ON CRON
      #
      ##########################################################





      ##########################################################
      # BIONIC DOCKER BUILD ON CRON
      ##########################################################
    - os: linux
      services: docker
      env:
        - TRAVIS_CONFIG=linux
        - DOCKER_COMPOSE=${TRAVIS_BUILD_DIR}/.docker/docker-compose.travis.yml
        # TRAVIS_BRANCH is either the git tag or the branch name when no tag
        - DOCKER_TAG=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && echo $TRAVIS_BRANCH | sed 's/master/latest/' || echo "latest" )
        - TRAVIS_TIMESTAMP=$(date +%s)
        - CCACHE_DIR=${HOME}/.ccache
        - DOCKER_DEBIAN_DISTRO=bionic
      if: type=cron

      ##########################################################
      # COSMIC DOCKER BUILD ON CRON
      ##########################################################
    - os: linux
      services: docker
      env:
        - TRAVIS_CONFIG=linux
        - DOCKER_COMPOSE=${TRAVIS_BUILD_DIR}/.docker/docker-compose.travis.yml
        # TRAVIS_BRANCH is either the git tag or the branch name when no tag
        - DOCKER_TAG=$( [[ $TRAVIS_REPO_SLUG =~ qgis/QGIS ]] && echo $TRAVIS_BRANCH | sed 's/master/latest/' || echo "latest" )
        - TRAVIS_TIMESTAMP=$(date +%s)
        - CCACHE_DIR=${HOME}/.ccache
        - DOCKER_DEBIAN_DISTRO=cosmic
      if: type=cron




    # OSX based build with QT4 and Python 2
#    - os: osx
#      osx_image: xcode8.3 # MacOS 10.12: Sierra
#      cache:
#        pip: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - TRAVIS_CONFIG=macos
#        - IGNORE_BUILD_FAILURES=YES
#
#  allow_failures:
#    - os: osx

git:
  depth: 120

notifications:
  irc: "chat.freenode.net#qgis-test"
  on_failure: change
  on_success: change
  skip_join: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/467e3aff72e344d1dae3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # default: never

before_install:
  - ./.ci/travis/${TRAVIS_CONFIG}/before_install.sh

install:
  - ./.ci/travis/${TRAVIS_CONFIG}/install.sh

before_script:
  - ./.ci/travis/${TRAVIS_CONFIG}/before_script.sh

script:
  - ./.ci/travis/${TRAVIS_CONFIG}/script.sh

after_script:
  - ./.ci/travis/${TRAVIS_CONFIG}/after_script.sh
