language: cpp

sudo: false
dist: precise
group: legacy

os:
  - linux

compiler:
  - clang

git:
  depth: 30


cache:
  apt: true
  ccache: true
  directories:
    - $HOME/deps

addons:
  postgresql: "9.4"
  apt:
    sources:
#      - llvm-toolchain-precise-3.7
#      - ubuntu-toolchain-r-test
    packages:
      - bison
      - flex
      - graphviz
      - grass-dev
      - libexpat1-dev
      - libfcgi-dev
      - libgeos-dev
      - libgsl0-dev
      - libpq-dev
      - libqca2-dev
      - libqca2-plugin-ossl
      - libqscintilla2-dev
      - libqt4-dev
      - libqt4-opengl-dev
      - libqt4-sql-sqlite
      - libqtwebkit-dev
      - libqwt-dev
      - libspatialindex-dev
      - libsqlite3-dev
      - pkg-config
      - poppler-utils
      - pyqt4-dev-tools
      - python
      - python-dev
      - python-qt4
      - python-qt4-dev
      - python-qt4-sql
      - python-sip
      - python-sip-dev
      - spawn-fcgi
      - txt2tags
      - xauth
      - xvfb
      - python-pip
      - flip
      - fftw-dev
      - libfreexl-dev
#      - clang-3.7
#      - llvm-3.7
#      - llvm-3.7-dev
#      - libstdc++-4.9-dev
#      - doxygen

#notifications:
#  irc: "chat.freenode.net#qgis-test"
#  on_failure: change
#  on_success: change
#  skip_join: true
#
#notifications:
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/467e3aff72e344d1dae3
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always # options: [always|never|change] default: always
#    on_start: never # default: never

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

after_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/after_script.sh
