
matrix:
  include:
    - os: linux
      language: cpp
      env: QT_VERSION=4
      sudo: false
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      compiler: clang
      addons:
        postgresql: "9.4"
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # doxygen 1.8.3
          packages:
            - bison
            - clang-3.6
            - doxygen
            - flex
            - flip
            - libfcgi-dev
            - libpq-dev
            - libqscintilla2-dev
            - libqt4-dev
            - libqt4-opengl-dev
            - libqt4-sql-sqlite
            - libqtwebkit-dev
            - libqwt-dev
            - libspatialindex-dev
            - libspatialite-dev
            - libsqlite3-dev
            - lighttpd
            - pkg-config
            - poppler-utils
            - pyqt4-dev-tools
            - python
            - python-dev
            - python-numpy
            - python-pip
            - python-psycopg2
            - python-qscintilla2
            - python-qt4-dev
            - python-qt4-sql
            - python-sip
            - python-sip-dev
            - txt2tags
            - xvfb

git:
  depth: 30

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

after_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/after_script.sh
