---
name: 🪟 Windows
on:
  push:
    branches:
      - vcpkg
      - release-**
  pull_request:
  release:
    types: ['published']


jobs:
  build:
    name: build (windows)
    runs-on: windows-2022

    steps:
      - name: 🐣 Checkout
        uses: actions/checkout@v3

      - name: 🐩 Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: 🧽 Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: 🌱 Install dependencies and generate project files
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          # Convert paths to bash compatible ones. Thanks to whoever decided to use drive letters and backslashes.
          SOURCE_DIR=$( cygpath "${WORKSPACE}" )

          cmake -S "${SOURCE_DIR}" \
                -B "${SOURCE_DIR}/build" \
                -G Ninja \
                -D CMAKE_BUILD_TYPE=Release \
                -D WITH_VCPKG=ON \
                -D VCPKG_TARGET_TRIPLET=x64-windows \
                -D VCPKG_HOST_TRIPLET=x64-windows \
                -D WITH_3D=OFF \
                -D WITH_BINDINGS=ON \
                -D ENABLE_TESTS=OFF \
                -D VCPKG_MANIFEST_FEATURES="process;gui;desktop;bindings" \
                -D BUILD_WITH_QT6=ON \
                -D USE_CCACHE=ON \
                -D "FLEX_EXECUTABLE=${SOURCE_DIR}/build/_deps/vcpkg-src/downloads/tools/win_bison/2.5.25/win_flex.exe" \
                -D "BISON_EXECUTABLE=${SOURCE_DIR}/build/_deps/vcpkg-src/downloads/tools/win_bison/2.5.25/win_bison.exe" \
                -D WITH_QTWEBKIT=OFF \
                -D NUGET_USERNAME=m-kuhn \
                -D NUGET_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: 🌋 Build
        run: |
          cmake --build "${{ github.workspace }}/build" --config Release

      - name: 📦 Package
        run: |
          cmake --install "${{ github.workspace }}/build" --config Release
